Update node.js.yml

diff --git a/.github/workflows/node.js.yml b/.github/workflows/node.js.yml
--- a/.github/workflows/node.js.yml
+++ b/.github/workflows/node.js.yml
@@ -1,6 +1,3 @@
-# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
-# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs
-
 name: Node.js CI
 
 on:
@@ -11,7 +8,6 @@ on:
 
 jobs:
   build:
-
     runs-on: ubuntu-latest
 
     strategy:
@@ -20,35 +16,42 @@ jobs:
         # See supported Node.js release schedule at https://nodejs.org/en/about/releases/
 
     steps:
-    - uses: actions/checkout@v3
-    - name: Use Node.js ${{ matrix.node-version }}
-      uses: actions/setup-node@v3
-      with:
-        node-version: ${{ matrix.node-version }}
-        cache: 'npm'
-    - run: npm install -f
-    - run: npm test -- --watch=false --browsers=ChromeHeadless
-    
-    - name: Archive test reports
-      uses: actions/upload-artifact@v3
-      if: success() || failure()
-      with:
-        name: karma_testReports
-        path: test-results/
+      - uses: actions/checkout@v3
 
-    - name: Deploy GitHub Pages
-      uses: JamesIves/github-pages-deploy-action@4.1.0
-      if: success() || failure()
-      with:
-        branch: main  
-        folder: test-results  
-       
-    - name: Display GitHub Pages Link
-      if: success() || failure()
-      run: |
-        echo "GitHub Pages link:"
-        echo "https://sayyed-muzammil04.github.io/Demo/"
-       
-    - name: Finalize
-      if: always()
-      run: echo "Artifacts generated and uploaded"
+      - name: Use Node.js ${{ matrix.node-version }}
+        uses: actions/setup-node@v3
+        with:
+          node-version: ${{ matrix.node-version }}
+          cache: 'npm'
+
+      - run: npm install -f
+
+      - run: npm test -- --watch=false --browsers=ChromeHeadless
+
+      - name: Archive test reports
+        uses: actions/upload-artifact@v3
+        if: success() || failure()
+        with:
+          name: karma_testReports
+          path: test-results/
+
+  deploy:
+    runs-on: ubuntu-latest
+    needs: build  # This indicates that the deployment job depends on the 'build' job
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v3
+
+      - name: Deploy GitHub Pages
+        uses: JamesIves/github-pages-deploy-action@4.1.0
+        if: always()  # This ensures the deployment runs even if the 'build' job fails
+        with:
+          branch: gh-pages  # Customize this to the branch you want to deploy to (e.g., gh-pages)
+          folder: test-results  # Adjust this to the folder containing your site's assets to be deployed
+
+      - name: Display GitHub Pages Link
+        if: always()  # This ensures the link is displayed even if the 'build' job fails
+        run: |
+          echo "GitHub Pages link:"
+          echo "https://sayyed-muzammil04.github.io/Demo/"
